In [1]:
import tensorflow as tf

In [2]:
def cube(x):
    return x ** 3

In [3]:
cube(2)

8

In [4]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

이제 tf.fuction()을 이용해 파이썬 함수를 텐서플로 함수로 바꿔보겠습니다.

In [5]:
tf_cube = tf.function(cube)
tf_cube

이렇게 만든 텐서플로 함수는 원래 파이썬 함수처럼 사용할 수 있고 동일한 결과(하지만 텐서입니다.)를 반환합니다.

In [6]:
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [7]:
tf_cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

내부적으로 tf.function()은 cube() 함수에서 수행되는 계산을 분석하고<br>
동일한 작업을 수행하는 계산 그래프를 생성합니다.

다른 방법으로 tf.function 데코레이더가 실제로 더 널리 사용됩니다.

In [8]:
@tf.function
def tf_cube(x):
    return x ** 3

In [9]:
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

원본 파이썬 함수는 텐서플로 함수의 python_function 속성으로 참조할 수 있습니다.

In [10]:
tf_cube.python_function(2)

8